sudo: false
language: node_js
node_js:
- 5
cache:
  directories:
  - node_modules
branches:
  only:
  - master
before_install:
- openssl aes-256-cbc -K $encrypted_491621c5ab65_key -iv $encrypted_491621c5ab65_iv
  -in deploy-key.enc -out deploy-key -d
after_success:
- npm run build
- chmod 400 deploy-key
- eval "$(ssh-agent -s)"
- ssh-add deploy-key
- git config --global user.name "Travis CI"
- git config --global user.email travis@spacet.me
- echo wonderful.software > dist/CNAME
- |
  node -e 'require("gulp").src("dist/**/*").pipe(require("gulp-gh-pages")({
    remoteUrl: "git@github.com:wonderfulsoftware/wonderful.software.git" }))'

